---
title: "Plot Main Figure 2"
output: html_notebook
---

## 01. Load libraries

```{r}
library(ggplot2)
library(dplyr)
library(plyr)
library(ggpubr)
library(ggsignif)
library(precrec)
```

## 02. Define constants

```{r}
OUTPUT.DIR <- "/Users/leework/Documents/Research/projects/project_ace/data/processed/figures"
EVALUATION.RESULTS.DIR <- "/Users/leework/Documents/Research/projects/project_ace/data/processed/02_benchmark_ace/01_benchmark_against_existing_tools/06_evaluation_results/300immunogenic_30nonimmunogenic_1dispersion_fnr0.00"
DECONVOLUTETHIS.DESIGN.FILE <- "/Users/leework/Documents/Research/projects/project_ace/data/raw/references/deconvolutethis_designs.csv"
ERRORBAR.WIDTH <- 0.4
BOXPLOT.WIDTH <- 0.8
MIN.SIMULATIONS <- 20
GROUPS <- c("ace-s_cem",
            "strandberg_emp",
            "strandberg_bay",
            "strandberg_bgs",
            "deconvolutethis",
            "repeated_emp")
SOLVER.COLORS <- c("ace-s_cem" = "#845EC2",
                   "repeated_emp" = "#ABABAA",
                   "deconvolutethis" = "#E5CE23",
                   "strandberg_bgs" = "#7fc0e7",
                   "strandberg_bay" = "#9CC25E",
                   "strandberg_emp" = "#7fa8c1")
```

## 03. Plot 2a

```{r}
df.evaluation.results <- data.frame()
for (tsv.file in Sys.glob(paste0(EVALUATION.RESULTS.DIR, "/*evaluation_results.tsv"))) {
  df.temp <- read.csv(tsv.file, sep = "\t")
  df.temp$group <- paste0(df.temp$configuration_method, "_", df.temp$deconvolution_method)
  df.evaluation.results <- rbind(df.evaluation.results, df.temp)
}
df.evaluation.results$group <- plyr::mapvalues(
  x = df.evaluation.results$group,
  from = c("ace-s_ace-cem",
           "ace-s_ace-em",
           "ace-s_ace-empirical",
           "ace-s_ace-lasso",
           "ace_ace-cem",
           "ace_ace-em",
           "ace_ace-empirical",
           "ace_ace-lasso",
           "randomized_ace-cem",
           "randomized_ace-em",
           "randomized_ace-empirical",
           "randomized_ace-lasso",
           "repeated_ace-em",
           "repeated_ace-empirical",
           "strandberg_strandberg-background-subtracted",
           "strandberg_strandberg_bayesian",
           "strandberg_strandberg-empirical",
           "ace-s_strom"),
  to = c("ace-s_cem",
         "ace-s_em",
         "ace-s_emp",
         "ace-s_lasso",
         "ace_cem",
         "ace_em",
         "ace_empirical",
         "ace_lasso",
         "random_cem",
         "random_em",
         "random_emp",
         "random_lasso",
         "repeated_em",
         "repeated_emp",
         "strandberg_bgs",
         "strandberg_bay",
         "strandberg_emp",
         "ace-s_strom")
)

plots <- list()
plots.idx <- 1
df.evaluation.results.temp <- df.evaluation.results[df.evaluation.results$group %in% GROUPS,]
for (num.peptides in c(120, 800)) {
  for (num.immunogenic.peptides in c(1,5,10,20,40)) {
    list.scores <- list()
    list.labels <- list()
    dsids <- c()
    mod.names <- c()
    idx <- 1
    dsid <- 1
    for (group in unique(df.evaluation.results.temp$group)) {
      df.temp <- df.evaluation.results.temp[
          (df.evaluation.results.temp$num_peptides == num.peptides) &
          (df.evaluation.results.temp$group == group) &
          (df.evaluation.results.temp$num_immunogenic_peptides == num.immunogenic.peptides),
      ]
      if (length(unique(df.temp$rep_id)) < MIN.SIMULATIONS) {
        next
      }
      for (rep.id in unique(df.temp$rep_id)) {
        df.temp_ <- df.temp[df.temp$rep_id == rep.id,]
        list.scores[[idx]] <- df.temp_$peptide_spot_count
        list.labels[[idx]] <- df.temp_$binding
        dsids <- c(dsids, dsid)
        mod.names <- c(mod.names, group)
        idx <- idx + 1
      }
      dsid <- dsid + 1
    }
    smmdat <- mmdata(scores = list.scores, 
                     labels = list.labels, 
                     modnames = mod.names, 
                     dsids = dsids)
    smcurves <- evalmod(smmdat, cb_alpha = 0.05)
    df.auc.ci <- auc_ci(smcurves)
    df.auc.ci.prc <- df.auc.ci[df.auc.ci$curvetypes == "PRC",]
    updated.legend <- c()
    for (i in 1:nrow(df.auc.ci.prc)) {
      df.curr <- df.auc.ci.prc[i,]
      curr.updated.legend <- c(paste0(df.curr$modnames, " (", round(df.curr$mean, 3), ")"))
      names(curr.updated.legend) <- df.curr$modnames
      updated.legend <- c(updated.legend, curr.updated.legend)
    }
    g <- autoplot(object = smcurves, curvetype = "PRC", show_cb = F)
    g <- g + 
      ggtitle(paste(num.peptides, "peptides", num.immunogenic.peptides, "positives")) + 
      scale_color_manual(values = SOLVER.COLORS,
                         labels = updated.legend) +
      labs(color = NULL) +
      theme(plot.title = element_text(size = 12),
            axis.title = element_text(size = 12),
            axis.text = element_text(size = 12),
            legend.text = element_text(size = 8),
            legend.position = c(0.65, 0.1),
            legend.spacing.x = unit(0.05, 'cm'),
            legend.spacing.y = unit(0.05, 'cm'),
            legend.margin = margin(0,0,0,0),
            legend.box.margin = margin(0,0,0,0),
            plot.margin = unit(c(0.05, 0.05, 0.05, 0.05), "lines"))
    plots[[plots.idx]] <- g
    plots.idx <- plots.idx + 1
  }
}

plot.2a <- ggarrange(plotlist = plots, nrow = 2, ncol = 5, align = "hv")
```

## 04. Plot 2b

```{r}
# Step 1. Load evaluation data
df.evaluation.metrics <- data.frame()
for (tsv.file in Sys.glob(paste0(EVALUATION.RESULTS.DIR, "/*evaluation_metrics.tsv"))) {
  df.temp <- read.csv(tsv.file, sep = "\t")
  df.temp$group <- paste0(df.temp$configuration_method, "_", df.temp$deconvolution_method)
  df.evaluation.metrics <- rbind(df.evaluation.metrics, df.temp)
}
df.evaluation.metrics$group <- plyr::mapvalues(
  x = df.evaluation.metrics$group,
  from = c("ace-s_ace-cem",
           "ace-s_ace-em",
           "ace-s_ace-empirical",
           "ace-s_ace-lasso",
           "ace_ace-cem",
           "ace_ace-em",
           "ace_ace-empirical",
           "ace_ace-lasso",
           "randomized_ace-cem",
           "randomized_ace-em",
           "randomized_ace-empirical",
           "randomized_ace-lasso",
           "repeated_ace-em",
           "repeated_ace-empirical",
           "strandberg_strandberg-background-subtracted",
           "strandberg_strandberg_bayesian",
           "strandberg_strandberg-empirical"),
  to = c("ace-s_cem",
         "ace-s_em",
         "ace-s_emp",
         "ace-s_lasso",
         "ace_cem",
         "ace_em",
         "ace_empirical",
         "ace_lasso",
         "random_cem",
         "random_em",
         "random_emp",
         "random_lasso",
         "repeated_em",
         "repeated_emp",
         "strandberg_bgs",
         "strandberg_bay",
         "strandberg_emp")
)

# Step 2. Drop any group with fewer than 20 simulations
for (num.peptides in unique(df.evaluation.metrics$num_peptides)) {
  for (group in unique(df.evaluation.metrics$group)) {
    for (num.immunogenic.peptides in unique(df.evaluation.metrics$num_immunogenic_peptides)) {
      df.matched <- df.evaluation.metrics[
        (df.evaluation.metrics$num_peptides == num.peptides) &
        (df.evaluation.metrics$group == group) & 
        (df.evaluation.metrics$num_immunogenic_peptides == num.immunogenic.peptides),
      ]
      if (nrow(df.matched) < MIN.SIMULATIONS) {
        df.evaluation.metrics <- df.evaluation.metrics[
          !(df.evaluation.metrics$experiment_id %in% df.matched$experiment_id),
        ]
      }
    }
  }
}

# Step 3. Append DeconvoluteThis rows
df.deconvolutethis <- read.csv(DECONVOLUTETHIS.DESIGN.FILE)
df.deconvolutethis <- df.deconvolutethis[df.deconvolutethis$num_coverage == 3,]
for (num.peptides in unique(df.evaluation.metrics$num_peptides)) {
  for (num.immunogenic.peptides in unique(df.evaluation.metrics$num_immunogenic_peptides)) {
    df.matched <- df.deconvolutethis[
      (df.deconvolutethis$num_peptides == num.peptides) &
      (df.deconvolutethis$num_true_positive_peptides == num.immunogenic.peptides),
    ]
    num.peptides.per.pool <- df.matched$num_peptides_per_pool[1]
    num.total.pools <- df.matched$num_deconvolutethis_total_pools[1]
    num.init.pools <- (num.peptides / num.peptides.per.pool) * 3
    num.predicted.positive.peptides <- num.total.pools - num.init.pools
    precision <- num.immunogenic.peptides / num.predicted.positive.peptides
    sensitivity <- 1.0
    df.temp <- data.frame(
      experiment_id = c(paste0("deconvolutethis_", num.peptides,"peptides")),
      predicted_total_pools = c(num.total.pools),
      precision = c(precision),
      sensitivity = c(sensitivity),
      specificity = c(NA),
      aucroc = c(NA),
      num_peptides = c(num.peptides),
      num_peptides_per_pool = c(num.peptides.per.pool),
      num_coverage = c(3),
      num_immunogenic_peptides = c(num.immunogenic.peptides),
      rep_id = c("rep1"),
      configuration_method = c("deconvolutethis"),
      deconvolution_method = c("deconvolutethis"),
      group = c("deconvolutethis")
    )
    df.evaluation.metrics <- rbind(df.evaluation.metrics, df.temp)
  }
}

# Step 4. Define functions
PlotBarPlot <- function(df.evaluation.metrics, metric, num.peptides, y.axis.title, title) {
  df.plot <- df.evaluation.metrics[df.evaluation.metrics$num_peptides == num.peptides,]
  df.plot <- df.plot %>%
    dplyr::group_by(group, num_immunogenic_peptides) %>%
    dplyr::summarise(
      sd = sd(get(metric)),
      metric = mean(get(metric))
    )
  df.plot$num_immunogenic_peptides <- as.character(df.plot$num_immunogenic_peptides)
  for (group in unique(df.plot$group)) {
    for (num.immunogenic.peptides in c("1","2","3","4","5","6","7","8","9","10","15","20","25","30","40")) {
      df.matched <- df.plot[(df.plot$group == group) & (df.plot$num_immunogenic_peptides == num.immunogenic.peptides),]
      if (nrow(df.matched) == 0) {
        df.temp <- data.frame(
          group = c(group),
          num_immunogenic_peptides = c(num.immunogenic.peptides),
          sd = c(0.0),
          metric = c(0.0)
        )
        df.plot <- rbind(df.plot, df.temp)
      }
    }
  }
  df.plot$num_immunogenic_peptides <- factor(
    df.plot$num_immunogenic_peptides,
    levels = c("1","2","3","4","5",
               "6","7","8","9","10",
               "15","20","25","30","40")
  )
  df.plot$group <- factor(
    df.plot$group,
    levels = GROUPS
  )
  p <- ggplot(df.plot, aes(x = num_immunogenic_peptides, y = metric, fill = group)) +
    geom_col(width = BOXPLOT.WIDTH, colour = "black", position = "dodge")
  if (metric == "precision" || metric == "sensitivity") {
    p <- p + geom_errorbar(aes(ymin = metric - sd, 
                               ymax = ifelse(metric + sd > 1, 1, metric + sd)), 
                           width = ERRORBAR.WIDTH, position = position_dodge(BOXPLOT.WIDTH)) +
          scale_y_continuous(limits = c(0,1), breaks = c(0.00, 0.25, 0.50, 0.75, 1.00), expand = c(0,0))
  }
  if (metric == "predicted_total_pools") {
    p <- p + geom_errorbar(aes(ymin = metric - sd, ymax = metric + sd),
                           width = ERRORBAR.WIDTH, position = position_dodge(BOXPLOT.WIDTH))
  }
  p <- p + xlab("Number of Positive Peptides") + ylab(y.axis.title) + ggtitle(title) +
    scale_fill_manual(values = SOLVER.COLORS) +
    theme_pubr() +
    theme(plot.title = element_text(size = 12, hjust = 0.5),
          axis.title = element_text(size = 12),
          axis.text.x = element_text(size = 12),
          axis.text.y = element_text(size = 12),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.title = element_text(size = 12),
          legend.text = element_text(size = 12),
          strip.text = element_text(size = 12),
          strip.background = element_rect(fill = "white"))
  return(p)
}

# Step 5. Generate plots
df.evaluation.metrics <- df.evaluation.metrics[df.evaluation.metrics$group %in% GROUPS,]
plot.120.peptides.precision <- PlotBarPlot(
  df.evaluation.metrics = df.evaluation.metrics,
  metric = "precision",
  num.peptides = 120,
  y.axis.title = "Precision",
  title = "120 peptides precision"
)
plot.120.peptides.recall <- PlotBarPlot(
  df.evaluation.metrics = df.evaluation.metrics, 
  metric = "sensitivity",
  num.peptides = 120, 
  y.axis.title = "Recall",
  title = "120 peptides recall"
)
plot.120.peptides.total.pools <- PlotBarPlot(
  df.evaluation.metrics = df.evaluation.metrics, 
  metric = "predicted_total_pools",
  num.peptides = 120, 
  y.axis.title = "Total Number of Pools",
  title = "120 peptides pools"
)
plot.800.peptides.precision <- PlotBarPlot(
  df.evaluation.metrics = df.evaluation.metrics,
  metric = "precision",
  num.peptides = 800,
  y.axis.title = "Precision",
  title = "800 peptides precision"
)
plot.800.peptides.recall <- PlotBarPlot(
  df.evaluation.metrics = df.evaluation.metrics,
  metric = "sensitivity",
  num.peptides = 800,
  y.axis.title = "Recall",
  title = "800 peptides recall"
)
plot.800.peptides.total.pools <- PlotBarPlot(
  df.evaluation.metrics = df.evaluation.metrics, 
  metric = "predicted_total_pools",
  num.peptides = 800, 
  y.axis.title = "Total Number of Pools",
  title = "800 peptides pools"
)
plot.2b <- ggarrange(plotlist = list(
  plot.120.peptides.precision, plot.800.peptides.precision,
  plot.120.peptides.recall, plot.800.peptides.recall,
  plot.120.peptides.total.pools, plot.800.peptides.total.pools),
  heights = c(3,2,3),
  nrow = 3, ncol = 2, align = "hv", common.legend = T
)
```

```{r}
figure.2 <- ggarrange(plotlist = list(plot.2a, plot.2b),
                      nrow = 2,
                      heights = c(1,1))
ggsave(filename = paste0(OUTPUT.DIR, "/main_figure_3.pdf"), 
       plot = figure.2, width = 16, height = 16, dpi = 300)
```
